/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iudigital.funcionario.test;

import com.iudigital.funcionario.controller.FuncionarioController;
import com.iudigital.funcionario.domain.Funcionario;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JR
 */
public class Main extends javax.swing.JFrame {

    private final FuncionarioController funFuncionarioController;
    private final static String[] COLUMNS = {"ID", "TIPOID", "NUMERODOCUMENTO", "NOMBRES", "APELLIDOS", "ESTADOCIVIL",
            "SEXO", "DIRECCION", "TELEFONO", "FECHANACIMIENTO"};
    private final static String SELECCIONE = "-SELECCIONE-";

    //constructores
    public Main() {
        initComponents();
        txtFuncionarioId.setEditable(false);
        funFuncionarioController = new FuncionarioController();
        listFuncionarios();
        addListener();

    }

    private void listFuncionarios() {

        cbxFuncionarios.removeAllItems();
        Funcionario funcionario1 = new Funcionario();
        funcionario1.setNombres(SELECCIONE);
        funcionario1.setApellidos("");
        cbxFuncionarios.addItem(funcionario1);

        DefaultTableModel defaulTableModel = new DefaultTableModel();
        for (String COLUMN : COLUMNS) {
            defaulTableModel.addColumn(COLUMN);
        }
        tblFuncionarios.setModel(defaulTableModel);

        try {
            List<Funcionario> funcionarios = funFuncionarioController.obtenerFuncionarios();
            if (funcionarios.isEmpty()) {
                return;
            }
            defaulTableModel.setRowCount((funcionarios.size()));
            int row = 0;
            for (Funcionario funcionario : funcionarios) {
                defaulTableModel.setValueAt(funcionario.getId(), row, 0);
                defaulTableModel.setValueAt(funcionario.getTipoid(), row, 1);
                defaulTableModel.setValueAt(funcionario.getNumerodocumento(), row, 2);
                defaulTableModel.setValueAt(funcionario.getNombres(), row, 3);
                defaulTableModel.setValueAt(funcionario.getApellidos(), row, 4);
                defaulTableModel.setValueAt(funcionario.getEstadocivil(), row, 5);
                defaulTableModel.setValueAt(funcionario.getSexo(), row, 6);
                defaulTableModel.setValueAt(funcionario.getDireccion(), row, 7);
                defaulTableModel.setValueAt(funcionario.getTelefono(), row, 8);
                defaulTableModel.setValueAt(funcionario.getFechanacimiento(), row, 9);
                row++;

                cbxFuncionarios.addItem(funcionario);

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void addListener() {
        cbxFuncionarios.addItemListener(event -> {
            Funcionario seledtedFun = (Funcionario) event.getItem();
            if (seledtedFun.getNombres().equals(SELECCIONE)) {
                txtFuncionarioId.setText("");
                txtTipoidEdit.setText("");
                txtNumerodocumentoEdit.setText("");
                txtNombresEdit.setText("");
                txtApellidosEdit.setText("");
                txtEstadocivilEdit.setText("");
                txtSexoEdit.setText("");
                txtDireccionEdit.setText("");
                txtTelefonoEdit.setText("");
                txtFechanacimientoEdit.setText("");

            } else {
                txtFuncionarioId.setText(String.valueOf(seledtedFun.getId()));
                txtTipoidEdit.setText(seledtedFun.getTipoid());
                txtNumerodocumentoEdit.setText(seledtedFun.getNumerodocumento());
                txtNombresEdit.setText(seledtedFun.getNombres());
                txtApellidosEdit.setText(seledtedFun.getApellidos());
                txtEstadocivilEdit.setText(seledtedFun.getEstadocivil());
                txtSexoEdit.setText(seledtedFun.getSexo());
                txtDireccionEdit.setText(seledtedFun.getDireccion());
                txtTelefonoEdit.setText(seledtedFun.getTelefono());
                txtFechanacimientoEdit.setText(seledtedFun.getFechanacimiento());

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Funcionario1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblTipoid = new javax.swing.JLabel();
        lblNumerodocumento = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblEstadocivil = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblFechanacimiento = new javax.swing.JLabel();
        txtTipoid = new javax.swing.JTextField();
        txtNumerodocumento = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtEstadocivil = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtFechanacimiento = new javax.swing.JTextField();
        btnCrear = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPfuncionario1 = new javax.swing.JPanel();
        lblFuncionarios = new javax.swing.JLabel();
        cbxFuncionarios = new javax.swing.JComboBox<>();
        lblFuncionarioId = new javax.swing.JLabel();
        txtFuncionarioId = new javax.swing.JTextField();
        lblTipoidEdit = new javax.swing.JLabel();
        txtTipoidEdit = new javax.swing.JTextField();
        lblNumerodocumentoEdit = new javax.swing.JLabel();
        txtNumerodocumentoEdit = new javax.swing.JTextField();
        lblNombresEdit = new javax.swing.JLabel();
        txtNombresEdit = new javax.swing.JTextField();
        lblApellidosEdit = new javax.swing.JLabel();
        txtApellidosEdit = new javax.swing.JTextField();
        lblEstadocivilEdit = new javax.swing.JLabel();
        txtEstadocivilEdit = new javax.swing.JTextField();
        lblSexoEdit = new javax.swing.JLabel();
        txtSexoEdit = new javax.swing.JTextField();
        lblDireccionEdit = new javax.swing.JLabel();
        txtDireccionEdit = new javax.swing.JTextField();
        lblTelefonoEdit = new javax.swing.JLabel();
        txtTelefonoEdit = new javax.swing.JTextField();
        lblFechanacimientoEdit = new javax.swing.JLabel();
        txtFechanacimientoEdit = new javax.swing.JTextField();
        btnEditar = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("GESTION DE FUNCIONARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite los sigientes campos"));

        lblTipoid.setText("Tipo ID");

        lblNumerodocumento.setText("Numero Documento");

        lblNombres.setText("Nombres");

        lblApellidos.setText("Apellidos");

        lblEstadocivil.setText("Estado Civil");

        lblSexo.setText("Sexo");

        lblDireccion.setText("Direccion");

        lblTelefono.setText("Telefono");

        lblFechanacimiento.setText("Fecha de nacimiento");

        txtNumerodocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerodocumentoActionPerformed(evt);
            }
        });

        btnCrear.setText("GUARDAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
        ));
        jScrollPane2.setViewportView(tblFuncionarios);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(56, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(lblSexo))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTipoid)
                                                        .addComponent(txtTipoid, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(lblNumerodocumento)
                                                                .addGap(55, 55, 55)
                                                                .addComponent(lblNombres)
                                                                .addGap(105, 105, 105)
                                                                .addComponent(lblApellidos)
                                                                .addGap(82, 82, 82)
                                                                .addComponent(lblEstadocivil))
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                                .addComponent(lblDireccion)
                                                                                .addGap(104, 104, 104)
                                                                                .addComponent(lblTelefono))
                                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                                .addComponent(txtNumerodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(txtEstadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                                .addGap(49, 49, 49)
                                                                                .addComponent(lblFechanacimiento))))))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtFechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(btnCrear))
                                        .addComponent(jScrollPane2))
                                .addGap(51, 51, 51))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTipoid)
                                        .addComponent(lblNumerodocumento)
                                        .addComponent(lblNombres)
                                        .addComponent(lblApellidos)
                                        .addComponent(lblEstadocivil))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTipoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNumerodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEstadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSexo)
                                        .addComponent(lblDireccion)
                                        .addComponent(lblTelefono)
                                        .addComponent(lblFechanacimiento))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCrear))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(230, 230, 230))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );

        Funcionario1.addTab("Crear Funcionario", jPanel1);

        jPfuncionario1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifique los  siguientes campos"));

        lblFuncionarios.setText("Funcionarios");

        lblFuncionarioId.setText("ID");

        lblTipoidEdit.setText("Tipo ID");

        lblNumerodocumentoEdit.setText("Numero Documento");

        txtNumerodocumentoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerodocumentoEditActionPerformed(evt);
            }
        });

        lblNombresEdit.setText("Nombres");

        lblApellidosEdit.setText("Apellidos");

        lblEstadocivilEdit.setText("Estado Civil");

        lblSexoEdit.setText("Sexo");

        lblDireccionEdit.setText("Direccion");

        txtDireccionEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionEditActionPerformed(evt);
            }
        });

        lblTelefonoEdit.setText("Telefono");

        lblFechanacimientoEdit.setText("Fecha de nacimiento");

        btnEditar.setText("GUARDAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPfuncionario1Layout = new javax.swing.GroupLayout(jPfuncionario1);
        jPfuncionario1.setLayout(jPfuncionario1Layout);
        jPfuncionario1Layout.setHorizontalGroup(
                jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPfuncionario1Layout.createSequentialGroup()
                                .addGroup(jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPfuncionario1Layout.createSequentialGroup()
                                                .addGroup(jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPfuncionario1Layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addGroup(jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblEstadocivilEdit)
                                                                        .addComponent(txtFuncionarioId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblFuncionarioId))
                                                                .addGap(27, 27, 27))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPfuncionario1Layout.createSequentialGroup()
                                                                .addComponent(txtEstadocivilEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtTipoidEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPfuncionario1Layout.createSequentialGroup()
                                                                .addComponent(lblTipoidEdit)
                                                                .addGap(36, 36, 36))
                                                        .addGroup(jPfuncionario1Layout.createSequentialGroup()
                                                                .addGap(9, 9, 9)
                                                                .addComponent(txtSexoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPfuncionario1Layout.createSequentialGroup()
                                                                .addGap(44, 44, 44)
                                                                .addComponent(lblSexoEdit)))
                                                .addGroup(jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPfuncionario1Layout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addComponent(txtDireccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPfuncionario1Layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPfuncionario1Layout.createSequentialGroup()
                                                                                .addComponent(lblNumerodocumentoEdit)
                                                                                .addGap(77, 77, 77)
                                                                                .addComponent(lblNombresEdit)
                                                                                .addGap(86, 86, 86)
                                                                                .addComponent(lblApellidosEdit))
                                                                        .addGroup(jPfuncionario1Layout.createSequentialGroup()
                                                                                .addComponent(txtNumerodocumentoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(26, 26, 26)
                                                                                .addComponent(txtNombresEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(txtApellidosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPfuncionario1Layout.createSequentialGroup()
                                                                                .addGap(175, 175, 175)
                                                                                .addComponent(txtTelefonoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(27, 27, 27)
                                                                                .addComponent(txtFechanacimientoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPfuncionario1Layout.createSequentialGroup()
                                                                                .addComponent(btnEliminar)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(btnEditar))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPfuncionario1Layout.createSequentialGroup()
                                                                .addGap(68, 68, 68)
                                                                .addComponent(lblDireccionEdit)
                                                                .addGap(106, 106, 106)
                                                                .addComponent(lblTelefonoEdit)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(lblFechanacimientoEdit)
                                                                .addGap(15, 15, 15))))
                                        .addGroup(jPfuncionario1Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblFuncionarios))))
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPfuncionario1Layout.setVerticalGroup(
                jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPfuncionario1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblFuncionarios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEditar)
                                        .addComponent(btnEliminar))
                                .addGap(29, 29, 29)
                                .addGroup(jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblFuncionarioId)
                                        .addComponent(lblTipoidEdit)
                                        .addComponent(lblNumerodocumentoEdit)
                                        .addComponent(lblNombresEdit)
                                        .addComponent(lblApellidosEdit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFuncionarioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTipoidEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNumerodocumentoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombresEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtApellidosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEstadocivilEdit)
                                        .addComponent(lblSexoEdit)
                                        .addComponent(lblDireccionEdit)
                                        .addComponent(lblTelefonoEdit)
                                        .addComponent(lblFechanacimientoEdit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPfuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtEstadocivilEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSexoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelefonoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFechanacimientoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDireccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPfuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jPfuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(121, Short.MAX_VALUE))
        );

        Funcionario1.addTab("Editar Funcionario", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 399, Short.MAX_VALUE)
        );



        getContentPane().add(Funcionario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 770, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumerodocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerodocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerodocumentoActionPerformed

    private void txtNumerodocumentoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerodocumentoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerodocumentoEditActionPerformed

    private void txtDireccionEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionEditActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (txtFuncionarioId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Selecciones un funcionario ");
            txtFuncionarioId.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }

        if (txtTipoidEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el tipo ID");
            txtTipoidEdit.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }

        if (txtNumerodocumentoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "digite Numero de documento");
            txtNumerodocumentoEdit.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtNombresEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Nombres");
            txtNombresEdit.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtApellidosEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Apellidos");
            txtApellidosEdit.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtEstadocivilEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite estado civil");
            txtEstadocivilEdit.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtSexoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite sexo");
            txtSexoEdit.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtDireccionEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite dirrecion");
            txtDireccionEdit.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtTelefonoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite telefono");
            txtTelefonoEdit.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtFechanacimientoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite fecha nacimiento");
            txtFechanacimientoEdit.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        //seteamos funcionario
        Funcionario funcionario = new Funcionario();
        funcionario.setTipoid(txtTipoidEdit.getText().trim());
        funcionario.setNumerodocumento(txtNumerodocumentoEdit.getText().trim());
        funcionario.setNombres(txtNombresEdit.getText().trim());
        funcionario.setApellidos(txtApellidosEdit.getText().trim());
        funcionario.setEstadocivil(txtEstadocivilEdit.getText().trim());
        funcionario.setSexo(txtSexoEdit.getText().trim());
        funcionario.setDireccion(txtDireccionEdit.getText().trim());
        funcionario.setTelefono(txtTelefonoEdit.getText().trim());
        funcionario.setFechanacimiento(txtFechanacimientoEdit.getText().trim());

        int opt = JOptionPane.showConfirmDialog(null, "Desea guardar los cambios?",
                "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {

            //creamos instancia de Funcionario
            try {

                funFuncionarioController.actualizarFuncionario(Integer.parseInt(txtFuncionarioId.getText()), funcionario);
                txtFuncionarioId.setText(""); // limpiamos los campos
                txtTipoidEdit.setText("");
                txtNumerodocumentoEdit.setText("");
                txtNombresEdit.setText("");
                txtApellidosEdit.setText("");
                txtEstadocivilEdit.setText("");
                txtSexoEdit.setText("");
                txtDireccionEdit.setText("");
                txtTelefonoEdit.setText("");
                txtFechanacimientoEdit.setText("");
                listFuncionarios();
                JOptionPane.showMessageDialog(null, "Los cambio se guardaron con exito");

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showInternalMessageDialog(null, "No se pudo guardar los cambios");
            }
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        if (txtTipoid.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el tipo ID");
            txtTipoid.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }

        if (txtNumerodocumento.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "digite Numero de documento");
            txtNumerodocumento.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }

        if (txtNombres.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Nombres");
            txtNombres.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtApellidos.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Apellidos");
            txtApellidos.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtEstadocivil.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite estado civil");
            txtEstadocivil.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtSexo.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite sexo");
            txtSexo.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtDireccion.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite dirrecion");
            txtDireccion.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtTelefono.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite telefono");
            txtTelefono.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }
        if (txtFechanacimiento.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite fecha nacimiento");
            txtFechanacimiento.requestFocus();// nos se;ala en campo que falta por llenar
            return;
        }

        try {
            Funcionario funcionario = new Funcionario();
            funcionario.setTipoid(txtTipoid.getText().trim());
            funcionario.setNumerodocumento(txtNumerodocumento.getText().trim());
            funcionario.setNombres(txtNombres.getText().trim());
            funcionario.setApellidos(txtApellidos.getText().trim());
            funcionario.setEstadocivil(txtEstadocivil.getText().trim());
            funcionario.setSexo(txtSexo.getText().trim());
            funcionario.setDireccion(txtDireccion.getText().trim());
            funcionario.setTelefono(txtTelefono.getText().trim());
            funcionario.setFechanacimiento(txtFechanacimiento.getText().trim());

            funFuncionarioController.crear(funcionario);
            txtTipoid.setText("");
            txtNumerodocumento.setText("");
            txtNombres.setText("");
            txtApellidos.setText("");
            txtEstadocivil.setText("");
            txtSexo.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtFechanacimiento.setText("");
            listFuncionarios();
            JOptionPane.showInternalMessageDialog(null, "Funcionario creado con exito");

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showInternalMessageDialog(null, "No se pudo crear Funcionario");
        }

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtFuncionarioId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione el Funcionario de la lista");
            txtFuncionarioId.requestFocus();
            return;
        }

        int opt = JOptionPane.showConfirmDialog(null, "Esta seguro de borrar este Funcionario?",
                "confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {
            try {
                funFuncionarioController.eliminarFuncionario(Integer.parseInt(txtFuncionarioId.getText()));
                txtFuncionarioId.setText("");
                txtNumerodocumento.setText("");
                txtNombres.setText("");
                txtApellidos.setText("");
                txtEstadocivil.setText("");
                txtSexo.setText("");
                txtDireccion.setText("");
                txtTelefono.setText("");
                txtFechanacimiento.setText("");
                listFuncionarios();
                JOptionPane.showMessageDialog(null, "Se elimiono el Funcionario con exito");
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Funcionario1;
    private javax.swing.JToggleButton btnCrear;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JComboBox<Funcionario> cbxFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPfuncionario1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblApellidosEdit;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccionEdit;
    private javax.swing.JLabel lblEstadocivil;
    private javax.swing.JLabel lblEstadocivilEdit;
    private javax.swing.JLabel lblFechanacimiento;
    private javax.swing.JLabel lblFechanacimientoEdit;
    private javax.swing.JLabel lblFuncionarioId;
    private javax.swing.JLabel lblFuncionarios;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNombresEdit;
    private javax.swing.JLabel lblNumerodocumento;
    private javax.swing.JLabel lblNumerodocumentoEdit;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSexoEdit;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefonoEdit;
    private javax.swing.JLabel lblTipoid;
    private javax.swing.JLabel lblTipoidEdit;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtApellidosEdit;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionEdit;
    private javax.swing.JTextField txtEstadocivil;
    private javax.swing.JTextField txtEstadocivilEdit;
    private javax.swing.JTextField txtFechanacimiento;
    private javax.swing.JTextField txtFechanacimientoEdit;
    private javax.swing.JTextField txtFuncionarioId;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNombresEdit;
    private javax.swing.JTextField txtNumerodocumento;
    private javax.swing.JTextField txtNumerodocumentoEdit;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtSexoEdit;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoEdit;
    private javax.swing.JTextField txtTipoid;
    private javax.swing.JTextField txtTipoidEdit;
    // End of variables declaration//GEN-END:variables
}
